import './modules/sidebar';
import './modules/cookies-simple';
import './modules/expand';
import './modules/password-strength';
import './modules/range-slider';
import './modules/currency-input';
import './modules/multiselect';
import './modules/dropzone';
import './modules/autocomplete';
